src/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.views.generic import list_detail
from django.contrib.auth.views import password_reset

from views import *
from models import News

urlpatterns = patterns('',
    url(r'^roles$', roles, name='roles'),
    url(r'^form', request_form, name='form'),
    url(r'^lock$', lock, name='lock'),
    url(r'^lock_rel$', lock_rel, name='lock_rel'),
    url(r'^news$', list_detail.object_list, {"queryset": News.objects.all()[5:]}, name='news'),
    url(r'^article/(?P<object_id>\d+)$', list_detail.object_detail, {'queryset': Article.objects.all()}, name='article'),
    url(r'^bus', bus, name='bus'),
    url(r'^food', food, name='food'),
    url(r'^rooms', rooms, name='rooms'),

    url(r'^reports/$', reports),
    url(r'^reports/contacts/$', report_contacts),
    url(r'^reports/paid/$', report_paid),
    url(r'^reports/layers/$', report_layers),
    url(r'^reports/players_without_roles/$', report_players_without_roles),
    url(r'^reports/food/$', report_food, name='report_food'),
    url(r'^reports/bus/$', report_bus, name='report_bus'),
    url(r'^reports/money/$', report_money, name='report_money'),
    url(r'^reports/full/$', report_full, name='report_full'),

    url(r'^$', index , name='index'),
    )

src/gallery/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *

from .views import gallery

urlpatterns = patterns('',
    url(r'^(\d+)$', gallery, name='gallery'),
    )

src/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, url, include, handler404, handler500
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^auth/login$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^auth/logout$', 'django.contrib.auth.views.logout', {'next_page':'/'}, name='logout'),
    url(r'^auth/password_reset$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^auth/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^auth/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    url(r'^auth/reset/done/$', 'django.contrib.auth.views.password_reset_complete'),

    url(r'^admin/', include(admin.site.urls), name="admin"),
    (r'^newspaper/', include('newspaper.urls')),
    (r'^gallery/', include('gallery.urls')),

    url(r'^messages/compose/$', 'core.views.messages_compose', name='messages_compose'),
    url(r'^messages/reply/(\d+)/$', 'core.views.reply', name='messages_compose'),
    (r'^messages/', include('messages.urls')),
    (r'^', include('core.urls')),
)

src/core/models.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

from yafotki.fields import YFField

from .utils import email


class GenericManager( models.Manager ):
    """
    Filters query set with given selectors
    """
    def __init__(self, **kwargs):
        super( GenericManager, self ).__init__()
        self.selectors = kwargs

    def get_query_set(self):
        return super( GenericManager, self ).get_query_set().filter( **self.selectors )


class RoleSection(models.Model):
    title = models.CharField(max_length=200, verbose_name=u"Название")
    order = models.IntegerField(verbose_name=u"Порядок", default=100)

    def __unicode__(self): return self.title

    class Meta:
        verbose_name = u"Раздел ролей"
        verbose_name_plural = u"Разделы ролей"
        ordering = ('order',)


class Role(models.Model):
    rolesection = models.ForeignKey(RoleSection, verbose_name=u"Раздел")
    name = models.CharField(max_length=200, verbose_name=u"ФИО")
    profession = models.CharField(max_length=200, verbose_name=u"Профессия")
    description = models.TextField(verbose_name=u"Описание", null=True, blank=True)
    cache = models.IntegerField(verbose_name=u"Наличность", default=0)
    account = models.IntegerField(verbose_name=u"Деньги на счете", default=0)

    order = models.IntegerField(verbose_name=u"Порядок", default=10000)
    profile = models.ForeignKey('Profile', verbose_name=u'Профиль', null=True, blank=True, related_name="locked_role")

    def __unicode__(self): return self.name

    def full_info(self):
        return u"[%s] %s, %s" % \
               (self.rolesection.title, self.name, self.profession)

    class Meta:
        verbose_name = u"Роль"
        verbose_name_plural = u"Роли"
        ordering = ('order',)


class Profile(models.Model):
    user = models.ForeignKey(User, verbose_name=u'Пользователь', null=True, blank=True)
    name = models.CharField(max_length=200, verbose_name=u"ФИО", null=True, blank=True)
    age = models.IntegerField(verbose_name=u"Возраст", null=True, blank=True)
    city = models.CharField(max_length=200, verbose_name=u"Город", null=True, blank=True)
    icq = models.CharField(max_length=200, verbose_name=u"ICQ", null=True, blank=True)
    tel = models.CharField(max_length=200, verbose_name=u"Телефон", null=True, blank=True)
    med = models.CharField(max_length=200, verbose_name=u"Медицинские особенности", null=True, blank=True)

    gun = models.CharField(max_length=200, verbose_name=u"Оружие", null=True, blank=True)
    goal = models.TextField(verbose_name=u"Цель")
    dream = models.TextField(verbose_name=u"Мечта", null=True, blank=True)
    portrait = YFField(
        verbose_name=u"Фото",
        upload_to='sincity',
        null=True, blank=True, default=None,
    )

    role = models.ForeignKey(Role, verbose_name=u"Роль", null=True, blank=True, related_name="suggested_role")
    quest = models.TextField(verbose_name=u'Квента', null=True, blank=True, default=None)

    paid = models.BooleanField(verbose_name=u"Взнос внесен", default=False)
    special = models.TextField(verbose_name=u'Спец. способности', null=True, blank=True, default=None)
    bus = models.BooleanField(verbose_name=u"Поедет автобусом", default=False)
    food = models.CharField(verbose_name=u"Питание", max_length=8, default='0'*8)
    room = models.ForeignKey('Room', verbose_name=u"Комната", null=True, blank=True, default=None)

    locked_fields = models.CharField(max_length="300", verbose_name=u"Замороженные поля", null=True, blank=True)

    def __unicode__(self): return self.user.username

    def form_link(self):
        return "<a href='" + reverse('form') + '?change_user=%s' % self.user.id + "'>анкета</a>"
    form_link.short_description = u"Анкета"
    form_link.allow_tags = True

    def print_link(self):
        return "<a href='" + reverse('report_full') + '?id=%s' % self.id + "'>печать</a>"
    print_link.short_description = u"Печать"
    print_link.allow_tags = True

    def user_email(self):
        return self.user.email
    user_email.short_description = u"Email"

    def user_username(self):
        return self.user.username
    user_username.short_description = u"Ник"

    def role_locked(self):
        if not self.role:
            return ''
        return self.role.profile == self and '+' or ''
    role_locked.short_description = u"Роль заморожена"

    def is_locked(self, field):
        return self.locked_fields and field in self.locked_fields

    def lock(self, field):
        if not self.locked_fields:
            self.locked_fields = ''
        if not self.is_locked(field):
            fields = self.locked_fields.split(',')
            fields.append(field)
            self.locked_fields = ",".join(fields)
            self.save()

            if field == 'role':
                self.role.profile = self
                self.role.save()

    def unlock(self, field):
        if not self.locked_fields:
            self.locked_fields = ''
        if self.is_locked(field):
            fields = self.locked_fields.split(',')
            fields.append(field)
            self.locked_fields = ",".join([f for f in fields if f != field])
            self.save()

            if field == 'role':
                self.role.profile = None
                self.role.save()


    def save(self, check_diff=True, *args, **kwargs):
        if self.pk and check_diff:
            prev = self.__class__.objects.get(pk=self.pk)
            report = ""
            for field in self._meta.fields:
                if field.name in('paid', 'locked_fields'):
                    continue

                if getattr(self, field.name) != getattr(prev, field.name):
                    report += u"%s: '%s' -> '%s'\n" % (field.verbose_name, getattr(prev, field.name) or '-', getattr(self, field.name) or '-')

            if report:
                email(
                    u"SinCity 2012: изменения в профиле игрока %s" % self.name,
                    u"Измененные поля профиля [http://sincity2012.ru/form?change_user=%s]:\n%s" % (self.user.pk, report),
                    [self.user.email],
                )

        return super(Profile, self).save(*args, **kwargs)

    class Meta:
        verbose_name = u"Профиль"
        verbose_name_plural = u"Профили"


class RoleConnection(models.Model):
    role = models.ForeignKey(Role, verbose_name=u"Роль", related_name='roles')
    role_rel = models.ForeignKey(Role, verbose_name=u"Связанная роль", related_name='linked_roles', null=True, blank=True)
    comment = models.TextField(verbose_name=u"Описание", null=True, blank=True, default=None)
    is_locked = models.BooleanField(verbose_name=u"Заморожено", default=False)

    def save(self, *args, **kwargs):
        if self.role.profile:
            emails = [self.role.profile.user.email]
        else:
            emails = []

        if self.pk:
            prev = self.__class__.objects.get(pk=self.pk)
            if getattr(self, 'comment') != getattr(prev, 'comment'):
                report = u"Анкета: http://sincity2012.ru/form?change_user=%s\n\nИзмененная связь: %s -> %s:\nБыло: %s\nСтало: '%s'" % \
                         (self.role.profile.user.pk, self.role,
                          self.role_rel, getattr(prev,'comment') or '-', getattr(self, 'comment') or '-')

                email(
                    u"SinCity 2012: изменения в связях роли %s" % self.role,
                    report,
                    emails,
                )
        else:
            if self.role.profile:
                profile = self.role.profile
            else:
                profile = Profile.objects.filter(role=self.role)[0]

            email(u"SinCity 2012: новая связь между ролями",
                u"Анкета: http://sincity2012.ru/form?change_user=%s\n\n%s -> %s\n\n%s"
                % (profile.user.pk, self.role, self.role_rel, self.comment),
                emails,
            )

        return super(RoleConnection, self).save(*args, **kwargs)

    class Meta:
        verbose_name = u"Связь ролей"
        verbose_name_plural = u"Связи ролей"


class Layer(models.Model):
    title = models.CharField(verbose_name=u"Название", max_length=200)

    def __unicode__(self): return self.title

    class Meta:
        verbose_name = u"Пласт"
        verbose_name_plural = u"Пласты"


class LayerConnection(models.Model):
    role = models.ForeignKey(Role, verbose_name=u"Роль")
    layer = models.ForeignKey(Layer, verbose_name=u"Пласт", related_name='roles')
    comment = models.TextField(verbose_name=u"Описание", null=True, blank=True, default=None)
    is_locked = models.BooleanField(verbose_name=u"Заморожено", default=False)

    def save(self, *args, **kwargs):
        emails = []
        if self.role and self.role.profile:
            emails.append(self.role.profile.user.email)
        if self.layer_id == 6:
            emails.append('linashyti@gmail.com')  # мастер по пласту "наука"

        if self.pk:
            prev = self.__class__.objects.get(pk=self.pk)
            if getattr(self, 'comment') != getattr(prev, 'comment'):
                report = u"Измененный пласт: %s -> %s:\nБыло: %s\nСтало: '%s'" % (self.role, self.layer, getattr(prev,'comment') or '-', getattr(self, 'comment') or '-')

                email(
                    u"SinCity 2012: изменения в пласте роли %s" % self.role,
                    report,
                    emails,
                )
        else:
            email(
                u"SinCity 2012: новый пласт роли %s" % self.role,
                u"%s -> %s\n\n%s" % (self.role, self.layer, self.comment),
                emails,
            )

        return super(LayerConnection, self).save(*args, **kwargs)

    class Meta:
        verbose_name = u"Связь с пластом"
        verbose_name_plural = u"Связи с пластами"

src/gallery/models.py
# -*- coding: utf-8 -*-

from django.db import models

from yafotki.fields import YFField

class Gallery(models.Model):
    title = models.CharField(max_length=200, verbose_name=u"Название")

    class Meta:
        verbose_name = u"Галерея"
        verbose_name_plural = u"Галереи"


class Photo(models.Model):
    gallery = models.ForeignKey(Gallery, verbose_name=u"Галерея")
    title = models.CharField(max_length=200, verbose_name=u"Название", null=True, blank=True, default=None)
    img = YFField(
        verbose_name=u"Фото",
        upload_to='sincity',
        null=True, blank=True, default=None,
    )

    class Meta:
        verbose_name = u"Фотография"
        verbose_name_plural = u"Фотографии"

src/gallery/views.py
# -*- coding: utf-8 -*-

from django.template import RequestContext
from django.shortcuts import get_object_or_404

from .models import Gallery, Photo


def render_to_response(request, template_name, context_dict=None):
    from django.shortcuts import render_to_response as _render_to_response
    context = RequestContext(request, context_dict or {})
    return _render_to_response(template_name, context_instance=context)


def gallery(request, gallery_id):
    return render_to_response(
        request,
        'gallery/gallery.html',
        {
            'gallery': get_object_or_404(Gallery, pk=gallery_id),
            'photos': Photo.objects.filter(gallery=gallery_id),
        }
    )

src/core/templates/base.html
{% load content %}{% load pytils_dt %}<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">

<head>
    <title>{% block title %}Sin City 2012{% endblock %}</title>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/>

    <link rel="stylesheet" href="{% MEDIA_URL %}main.css?3"/>

    <script type="text/javascript" src="http://yandex.st/jquery/1.6.2/jquery.min.js" charset="utf-8"></script>
	<script src="{% MEDIA_URL %}js/dropdown.js" type="text/javascript"></script>

    {% block head %}{% endblock %}
</head>
<body>
<!-- start: wrapper -->
<div id="wrapper">

<!-- start: header -->
<table class="b-header">
    <tr>
        <td class="b-header_left"><img src="{% MEDIA_URL %}i/header_left.jpg" /></td>
        <td class="b-header_center"><h1><a href="/">Sin City 2012</a></h1></td>
        <td class="b-header_right"><img src="{% MEDIA_URL %}i/header_right.jpg" /></td>
    </tr>
</table>
<!-- end: header -->

<!-- NOTE: top page menu inserted here -->
<!-- start: top page menu -->
	{% navigation %}
<!-- end: top page menu -->

<div id="container">
<table class="main">
	<tr>
		<td>
			<div class="sidebar">
                {% left_menu %}

                {% if user %}
                    Привет, {{ user.username }}
                    <br><a href="{% url messages_inbox %}">
                       {% if messages_inbox_count %}Новых сообщений: {{ messages_inbox_count }}
                       {% else %}личная почта
                       {% endif %}</a>

                    {% if is_superuser %}
                       <div><a href="/admin/">Админка</a></div>
                       <div><a href="/reports/">Отчеты</a></div>
                    {% endif %}

                    <br><a href="{% url logout %}">Выйти</a>
                    <br /><br />
                {% else %}
                    <a href="{% url login %}" title="Войти">Войти на сайт</a>
                {% endif %}
			</div>

		</td>

		<td class="content_zone">
			<div id="content">
				{% block content %}
				{% endblock %}
			</div>
		</td>

	</tr>
</table>
</div>



<!-- start: footer -->

<div id="footer">

<span class="footercredits">Copyright &#169; 2011 <a href="http://sincity2012.ru">Sin City 2012</a></span>

</div>
<!-- end: footer -->


</div>

<!-- end: wrapper -->


{% if not is_devel %}
    <!-- Yandex.Metrika counter -->
    <div style="display:none;"><script type="text/javascript">
        (function(w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter12224113 = new Ya.Metrika({id:12224113, enableAll: true, webvisor:true});
                }
                catch(e) { }
            });
        })(window, "yandex_metrika_callbacks");
    </script></div>
    <script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
    <noscript><div><img src="//mc.yandex.ru/watch/12224113" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
	<!-- /Yandex.Metrika counter -->
{% endif %}
</body>
</html>

src/core/templates/bus.html
{% extends "base.html" %}
{% load content %}

{% block content %}
    <h2>Автобус</h2>

	{% if profile %}
		<p>
		{% if profile.bus %}
			Я передумал, я <a href="?bus=off">не поеду</a> на общем автобусе.
		{% else %}
			Я <a href="?bus=on">тоже хочу</a> поехать на общем автобусе.
		{% endif %}
		</p>
	{% endif %}

	<p>{% if passangers %}
		Уже едут:
		{% for profile in passangers %}
			{{ profile.name }}{% if not forloop.last%},{% endif %}
		{% endfor %}
		(итого: {{ passangers|length }}).

		{% else %}
			Пока никого нет, вы будете первым.
		{% endif %}
	</p>
{% endblock %}

src/core/templates/food.html
{% extends "base.html" %}
{% load content %}

{% block head %}
    <script type="text/javascript">
        var food = [{% for day in cost %}{{ day }}{% if not forloop.last %}, {% endif %}{% endfor %}];
        $(function(){
            for(var i = 0; i < food.length; i ++){
                $('#id_field_' + i).click(function(){
                    recalc_cost();
                })
            };

            recalc_cost();
        })

        function recalc_cost(){
            var sum = 0;
            for(var i = 0; i < food.length; i ++){
                if($('#id_field_' + i).attr('checked') == 'checked'){
                    sum += food[i];
                }
            }
            $('#sum').text(sum);
        }
    </script>
{% endblock %}

{% block content %}
    <h2>Запись на питание</h2>

    {% if save %}
        <p>Заявка успешно сохранена.</p><br>
    {% endif %}

    <form action="" method="POST">
        {{ form.as_p }}
        <input type="hidden" name="action" value="1">
        <br>
        Общая сумма: <span id="sum"></span> руб. &nbsp; <input type="submit" value="Сохранить">
    </form>

{% endblock %}

src/core/templates/form.html
{% extends "base.html" %}
{% load content %}

{% block content %}
    <h1>Форма заявки</h1>
    {% if reg_form %}
        <div>Если вы уже регистрировались на этом сайте, войдите <a href="{% url login %}">здесь</a>.</div><br>
        {% if message %}
            <div>{{ message }}</div><br>
        {% endif %}
    {% endif %}

    <form action="" method="POST" enctype="multipart/form-data">
        {% if current_user %}
            <input type="hidden" name="change_user" id="id_change_user" value="{{ current_user }}" />
        {% endif %}

        {% include "form/tabs.html" %}

        {% include "form/profile.html" %}

        {% include "form/connections.html" %}

        {% include "form/quest.html" %}

        {% include "form/layers.html" %}

        <input type="submit" value="Сохранить" style="margin-left: 200px; padding: 5 20; font-size: 150%"/>

    </form>

    <script>
      function update_role_fields(){
            var role_id = $("#id_role").attr('value');
            if( role_id == '0'){
                $("#id_role_name").removeAttr('disabled').attr('value', '');
                $("#id_role_profession").removeAttr('disabled').attr('value', '');
                $('.special_role').show();
            }else{
                $("#id_role_name").attr('disabled', 'disabled').attr('value', roles[role_id][1]);
                $("#id_role_profession").attr('disabled', 'disabled').attr('value', roles[role_id][3]);
                $('.special_role').hide();
            }
            recalc();
      }

      roles = { {% for role in profile_form.roles %}
               '{{ role.pk }}': ['{{ role.name }}', '{{ role.profession }}']{% if not forloop.last %}, {% endif %}
               {% endfor %}
      };

      $(function(){
        $("#id_role").change(update_role_fields);
        update_role_fields();
      });


      function lock(field, action){
        $.getJSON('/lock?field='+field+'&action='+action+'&change_user='+$('#id_change_user').attr('value'),
                  function(data){
                      if(data.success){
                        if(action == 'lock'){
                            $('#'+field+'_lock').hide();
                            $('#'+field+'_unlock').show();
                        }else{
                            $('#'+field+'_lock').show();
                            $('#'+field+'_unlock').hide();
                        }
                    }else{
                        alert(data.error);
                    }
                  });
        return false;
      };

      function lock_rel(rel, action){
        $.getJSON('/lock_rel?rel='+rel+'&action='+action+'&change_user='+$('#id_change_user').attr('value'),
                  function(data){
                      if(data.success){
                        if(action == 'lock'){
                            $('#rel_'+rel+'_lock').hide();
                            $('#rel_'+rel+'_unlock').show();
                        }else{
                            $('#rel_'+rel+'_lock').show();
                            $('#rel_'+rel+'_unlock').hide();
                        }
                    }else{
                        alert(data.error);
                    }
                  });
        return false;
      };
      </script>
{% endblock %}

src/core/templates/gallery.html
{% extends "base.html" %}
{% load content %}

{% block content %}
    <h2>{{ gallery.title }}</h2>
    {% for photo in photos %}
        <div style="float: left; margin-right: 10px;">
            <div style="text-align: center">
                <a href="{{ photo.image.url }}" class="b-black-link"><img src="{% MEDIA_URL %}{{ photo.image.get_thumbnail.0 }}"></a><br>
                {{ photo.title|default:"&nbsp;" }}
            </div>
        </div>
    {% endfor %}
{% endblock %}

src/core/templates/index.html
{% extends "base.html" %}
{% load pytils_dt %}

{% block content %}
	{% for announce in news %}
		<div class="post" id="post-{{ announce.id }}">
			<h2>{{ announce.title }}</h2>
				{{ announce.date_created|ru_strftime:"%d %B" }}

		 	<div class="entry">
				  <p>{{ announce.content|safe|linebreaks }}</p>
			 </div>
		</div>
	{% endfor %}
	<p><a href="{% url news %}">остальные новости &gt;&gt;</a></p>
{% endblock %}

src/core/templates/last_news.html
{% load pytils_dt %}

<div class="b-news">
	{% for announce in news %}
		<div class="b-news_date">{{ announce.date_created|ru_strftime:"%d %B" }}</div>
		<div class="b-news_content">{{ announce.content|safe }}</div>
	{% endfor %}

	<div style="font-size: 80%; margin-bottom: 5px;"><a href="/news" title="Новости">все новости &gt;&gt;</a></div>
</div>

src/core/templates/lock_buttons.html
{% load content %}
{% if field %}
     <img src="{% MEDIA_URL %}i/lock-unlock.png" id='{{ field }}_lock' {% if locked %}style="display:none"{% endif %} onclick="lock('{{ field }}', 'lock')" title="Заблокировать">
     <img src="{% MEDIA_URL %}i/lock.png" id='{{ field }}_unlock' {% if not locked %}style="display:none"{% endif %} onclick="lock('{{ field }}', 'unlock')" title="Разблокировать">
{% endif %}

src/core/templates/lock_buttons_rel.html
{% load content %}
{% if rel %}
     <img src="{% MEDIA_URL %}i/lock-unlock.png" id='rel_{{ rel.id }}_lock' {% if locked %}style="display:none"{% endif %} onclick="lock_rel('{{ rel.id }}', 'lock')" title="Заблокировать">
     <img src="{% MEDIA_URL %}i/lock.png" id='rel_{{ rel.id }}_unlock' {% if not locked %}style="display:none"{% endif %} onclick="lock_rel('{{ rel.id }}', 'unlock')" title="Разблокировать">
{% endif %}

src/core/templates/locked_connections.html
{% load content %}
{% if connections %}
    <h2>Замороженные связи</h2>
    <table>
    {% for connection in connections %}
        <tr>
            <td style="vertical-align: top; font-weight: bold;">{{ connection.role_rel.name }}:</td>
            <td>{{ connection.comment|linebreaks }}</td>
            <td style="vertical-align: bottom;">{% if is_superuser %}{% locker_rel connection "" is_superuser %}{% endif %}</td>
        </tr>
    {% endfor %}
    </table>
    <br>
{% endif %}

src/core/templates/login.html
{% extends "base.html" %}
{% load content %}

{% block content %}
    <h1>Вход на сайт</h1>
    <div>{% if form.data and not form.is_valid %}Ошибка заполнения формы.{% endif %}</div>
    <form action="" method="POST">
        {% csrf_token %}
        Ник: {{ form.username }}<br>
        Пароль: {{ form.password }} &nbsp;
        <input type="submit" value="Войти">
    </form>

    <br>
    <p>Если вы еще не регистрировались на сайте, заполните пожалуйста <a href="/form">анкету игрока</a>.</p>
    <p>Если вы забыли пароль, его можно <a href="{% url password_reset %}">сменить</a>.</p>
    
{% endblock %}

src/core/templates/roles.html
{% extends "base.html" %}
{% load content %}

{% block head %}
    <script type="text/javascript" src="{% MEDIA_URL %}js/jquery.ui.core.js"></script>
    <script type="text/javascript" src="{% MEDIA_URL %}js/jquery.ui.widget.js"></script>
    <script type="text/javascript" src="{% MEDIA_URL %}js/jquery.ui.position.js"></script>
    <script type="text/javascript" src="{% MEDIA_URL %}js/jquery.ui.tooltip.js"></script>
	  <script>
	  $(document).ready(function(){
	    $(".b-roles").tooltip();
	  });
	  </script>

{% endblock %}

{% block content %}
    <div class="level_panel">
    {% for level in levels %}
        <a class="level_link" href="/roles?level={{ level.0 }}">
	        <span class="level_tab {% ifequal level.0 current_level%}level_tab_current{% endifequal %}">
	            {{ level.1 }}
	        </span>
        </a> &nbsp;
    {% endfor %}
    </div>

    <table class="b-roles" cellspacing="0">
        <tr class="b-roles_header">
			<th>Раздел</th>
            <th>Имя персонажа</th>
            <th>Профессия</th>
            <th>Игрок</th>
        </tr>
        {% for role in roles %}
            <tr class="{% cycle 'odd' 'even' %}{% if role.first %} role_separator{% endif %}">
				<td style="font-size: 80%">{{ role.rolesection.title }}</td>
                <td><div title="{{ role.description }}">{{ role.name }}</div></td>
                <td>{{ role.profession }}</td>
                <td>{% if role.profile %}
                        {% if user %}
                            {% if is_superuser %}
                                {{ role.profile.name }} ({{ role.profile.user.username }})&nbsp;
                            {% endif %}
                             <a href="{% url messages_compose %}?recipient={{ role.id }}" title="Личное сообщение"
                                ><img class="img_link" src="{% MEDIA_URL %}i/email.png"></a>
                        {% else %}
                            <img class="img_link" src="{% MEDIA_URL %}i/email.png" title="Зарегистрируйтесь, чтобы отправлять сообщения">
                        {% endif %}
                    {% else %}
                        &nbsp;
                    {% endif %}</td>
            </tr>
        {% endfor %}
    </table>


{% endblock %}

src/core/templates/rooms.html
{% extends "base.html" %}
{% load content %}

{% block content %}
    <h2>Расселение</h2>
    <p>При выборе комнаты обращайте внимание, что буквенно-цифровой номер слева - номер комнаты, а цифра справа - количество мест в комнате.</p>

    {% if message %}
        <p style="font-weight: bold">{{ message }}</p>
    {% endif %}

    {% if profile and profile.room %}
        <p>Я забронировал комнату {{ profile.room.title }}.</p>
    {% endif %}

    <p style="float: left; padding-right: 5px;">Первый этаж<br><img src="http://img-fotki.yandex.ru/get/6613/19044756.143/0_9699a_588568_XL"><br><br>
        Третий этаж<br>
        <img src="http://img-fotki.yandex.ru/get/6513/19044756.143/0_9699b_f9a03c46_XL"></p>

    {% regroup profiles by room.title as profiles_list %}

    {% for group in profiles_list %}
        {{ group.grouper }}: {% for profile in group.list %}{{ profile.role.name }}{% if not forloop.last %}, {% endif %}{% endfor %}
        {% if not forloop.last %}<br>{% endif %}
    {% endfor %}

    {% if can_reserve %}
        <p>
            <form action="" method="POST">
                Я хочу жить в комнате
                <select name="room">
                    {% for room in available_rooms %}
                    <option value="{{ room.id }}">{{ room.title }} &nbsp;</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Сохранить">
            </form>
        </p>
    {% endif %}
{% endblock %}